name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 3 : Lancer Flake8 pour vérifier le style
      - name: Run linting
        run: |
          pip install flake8
          flake8 app.py || true  # Permet de ne pas bloquer le workflow en cas d'erreur

      # Étape 4 : Construire et pousser l'image Docker
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.MonDataa }}
          password: ${{ secrets.docker_pro }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/checksum-app:latest

